### PR TITLE
FD-001: add readme

### PR DESCRIPTION
**Pull request by fidiego**
@InclusionOrg/inclusion-django-pokedex 

This is a super simple PR that just adds a nearly empty README.md

### CODE REVIEW

**Comment by fidiego** [comment]
@InclusionOrg/inclusion-django-pokedex 
Hey

**Comment by fidiego** [comment]
@InclusionOrg/inclusion-django-pokedex 
Hey

**Comment by Junmr4** [comment]
LGTM 🍡

**Comment by jasminestewart** [comment]
Looks good to me

**Pull request merged**
